#!/usr/bin/env python3
"""Generates streamlit/CONTRACT.md from indicators.py.

    make dashboard-contract

WHY GENERATED AND NOT HAND-WRITTEN. The CONTRACT exists for REVIEW: someone reads the query
alongside the explanation and decides whether the indicator is right before rebuilding it in
Power BI. If the two lived in different files, they would diverge at the first SQL tweak —
and the review would keep "passing", because nobody reads a SQL query and a text side by side
looking for disagreement.

It's the same mechanism as `docs/warehouse-evidence/` and the STAGE's DDL: the document is
derived from the thing, so there's no second place where the truth lives.

What this script does NOT do: it doesn't connect to anything. The CONTRACT is reviewable
without credentials, without Snowflake and without network — like `make warehouse-ddl`.
"""

from __future__ import annotations

import hashlib
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import indicators as I  # noqa: E402

DESTINO = os.path.join(os.path.dirname(os.path.abspath(__file__)), "CONTRACT.md")
ORIGEM = os.path.join(os.path.dirname(os.path.abspath(__file__)), "indicators.py")


def origem_sha256() -> str:
    """sha256 of indicators.py.

    It is NOT a clock, and that's the point. A timestamp would change on every run and
    leave the generated file eternally "modified" in git — which trains whoever reviews it
    to ignore the diff, precisely in the file where the diff is the only review. With the
    source's hash, `make dashboard-contract` over an up-to-date CONTRACT doesn't change a
    byte, and `git diff --exit-code` becomes a test that the two never diverged.
    """
    with open(ORIGEM, "rb") as arquivo:
        return hashlib.sha256(arquivo.read()).hexdigest()


def render() -> str:
    origem = origem_sha256()
    grupos: dict[str, list] = {}
    for indicador in I.INDICADORES:
        grupos.setdefault(indicador.grupo, []).append(indicador)

    linhas = [
        "# Panel indicators contract",
        "",
        "**Generated by `make dashboard-contract`.** Do not hand-edit: this file is derived",
        "from [`indicators.py`](indicators.py), which is where the query and the explanation",
        "live together. Editing here creates a second place where the indicator lives, and the",
        "two diverge at the first SQL tweak — with the cruel detail that the review would keep",
        "passing, because nobody reads a SQL query and a text side by side looking for disagreement.",
        "",
        f"Derived from `indicators.py` sha256 `{origem}`. The header carries the source's hash",
        "and **not** the generation date: this way regenerating an up-to-date contract doesn't",
        "change a byte, and `git diff --exit-code streamlit/CONTRACT.md` after",
        "`make dashboard-contract` is the check that the two never diverged.",
        "",
        "## What it's for",
        "",
        "Reviewing each indicator **before** rebuilding it in Power BI. For each one:",
        "the question it answers, the source's grain, whether the data is observed or",
        "synthetic, the exact SQL the panel runs, and the **gotchas** — the cases where the",
        "obvious measure produces a plausible and wrong number, which is the only class of",
        "error no test catches.",
        "",
        "## Boundary and credentials",
        "",
        "| | |",
        "|---|---|",
        f"| Target | `{I.DB}.MART` — and **only** MART |",
        "| Role | `RETAIL_READER`, the BI role. Reads MART; denied on GOLD and STAGE |",
        "| Session | opens with `use secondary roles none` — without it the restriction would pass by mistake |",
        "| Authentication | RSA key pair, from `~/.snowflake/config.toml`. No secret in the repo |",
        "| Writes | none. The panel doesn't create, alter or delete anything |",
        "",
        "The panel runs a live probe that confirms the denial on GOLD and STAGE, because a",
        "panel that claims to respect a boundary without demonstrating it is asking for trust.",
        "",
        "## Parameters",
        "",
        "Every query with a date axis accepts three bound parameters, never concatenated —",
        "so there's no way to inject anything through the interface's selector:",
        "",
        "| Parameter | Type | Use |",
        "|---|---|---|",
        "| `%(inicio)s` | ISO date | lower bound, inclusive |",
        "| `%(fim)s` | ISO date | upper bound, inclusive |",
        "| `%(armazens)s` | comma-separated list | `array_contains(wh::variant, split(%(armazens)s, ','))` |",
        "",
        "Indicators marked **no date axis** ignore `inicio`/`fim`: they bring the current",
        "version.",
        "",
        "## Index",
        "",
    ]

    for grupo in sorted(grupos):
        linhas.append(f"- **{grupo}**")
        for indicador in grupos[grupo]:
            linhas.append(f"  - [{indicador.titulo}](#{indicador.chave})")
    linhas += ["- [What the panel does NOT show](#what-the-panel-does-not-show)", ""]

    for grupo in sorted(grupos):
        linhas += [f"## {grupo}", ""]
        for indicador in grupos[grupo]:
            linhas += [
                f'<a id="{indicador.chave}"></a>',
                f"### {indicador.titulo}",
                "",
                "| | |",
                "|---|---|",
                f"| Key | `{indicador.chave}` |",
                f"| Question | {indicador.pergunta} |",
                f"| Source grain | `{indicador.grao}` |",
                f"| Data type | {indicador.tipo} |",
                f"| Marts | {', '.join(f'`{m}`' for m in indicador.marts)} |",
                f"| Date axis | {'yes' if indicador.datado else '**no** — current version'} |",
                "",
            ]
            if indicador.armadilhas:
                linhas += ["**Gotchas when rebuilding in Power BI**", ""]
                linhas += [f"{n}. {texto}" for n, texto in enumerate(indicador.armadilhas, 1)]
                linhas += [""]
            linhas += ["```sql", indicador.sql.strip(), "```", ""]

    linhas += [
        "## What the panel does NOT show",
        "",
        "A list of declared absences is worth more than an invented indicator. Each item",
        "carries the **trigger** that would unlock it, so the conversation is about what's",
        "missing and not about what could be approximated.",
        "",
    ]
    for titulo, motivo, gatilho in I.FORA_DE_ALCANCE:
        linhas += [f"### {titulo}", "", motivo, "", f"**Trigger:** {gatilho}", ""]

    linhas += [
        "---",
        "",
        "## Auxiliary queries",
        "",
        "Not business indicators. `FRESCOR` is what makes a new load **visible**:",
        "without it, the numbers change and nobody knows the base changed.",
        "",
        "```sql",
        I.FRESCOR.strip(),
        "```",
        "",
        "```sql",
        I.JANELA.strip(),
        "```",
        "",
        "```sql",
        I.ARMAZENS.strip(),
        "```",
        "",
    ]
    return "\n".join(linhas) + "\n"


def main() -> int:
    texto = render()
    temporario = DESTINO + ".tmp"
    with open(temporario, "w", encoding="utf-8") as arquivo:
        arquivo.write(texto)
    os.replace(temporario, DESTINO)
    print(f"escrito em ....... {os.path.relpath(DESTINO)}")
    print(f"origem sha256 .... {origem_sha256()}")
    print(f"indicadores ...... {len(I.INDICADORES)}")
    print(f"fora de alcance .. {len(I.FORA_DE_ALCANCE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
