#!/usr/bin/env python3
"""Generates streamlit/PRICE_CONTRACT.md from price_indicators.py.

    make price-dashboard-contract

Same mechanism as `contract.py`/`CONTRACT.md`, kept as a SEPARATE generator rather than a
parametrized one: the two panels' indicator catalogs already diverge in shape (this one has
no `FORA_DE_ALCANCE` list, and gained `produtos_buscaveis` — an indicator with `datado=False`
that exists to feed the search box, not to be read as a standalone number), and forcing both
through one generator would mean one file with two audiences instead of two small ones.
"""

from __future__ import annotations

import hashlib
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import price_indicators as PI  # noqa: E402

DESTINO = os.path.join(os.path.dirname(os.path.abspath(__file__)), "PRICE_CONTRACT.md")
ORIGEM = os.path.join(os.path.dirname(os.path.abspath(__file__)), "price_indicators.py")


def origem_sha256() -> str:
    """sha256 of price_indicators.py — not a generation date, see contract.py's twin
    docstring for why a timestamp would make this file eternally "modified" in git."""
    with open(ORIGEM, "rb") as arquivo:
        return hashlib.sha256(arquivo.read()).hexdigest()


def render() -> str:
    origem = origem_sha256()
    grupos: dict[str, list] = {}
    for indicador in PI.INDICADORES:
        grupos.setdefault(indicador.grupo, []).append(indicador)

    linhas = [
        "# Price-watch panel indicators contract",
        "",
        "**Generated by `make price-dashboard-contract`.** Do not hand-edit: this file is",
        "derived from [`price_indicators.py`](price_indicators.py). Editing here creates a",
        "second place where the indicator lives, and the two diverge at the first SQL tweak.",
        "",
        f"Derived from `price_indicators.py` sha256 `{origem}`. The header carries the",
        "source's hash and **not** the generation date, so regenerating an up-to-date",
        "contract doesn't change a byte.",
        "",
        "## What it's for",
        "",
        "A dedicated, exclusive view of Mercadona catalog price movement — drops, rises,",
        "category volatility, per-product history — separate from the operations dashboard",
        "(`app.py`/`CONTRACT.md`), which covers orders, fulfillment, stock and demand.",
        "",
        "## Boundary and credentials",
        "",
        "| | |",
        "|---|---|",
        f"| Target | schema `{PI.MART}` — and **only** `mart_price_evolution` / "
        "`mart_assortment_daily` |",
        "| Role | `retail_reader`, the same BI role the operations dashboard wears. "
        "Reads MART; denied on GOLD and STAGE |",
        "| Session | opens with `set role retail_reader` via `connection.py` — shared, "
        "unmodified, with the operations dashboard |",
        "| Authentication | local dev user/password, defaulted in `postgres_load.py` and "
        "overridable via `.env`. No secret in the repo |",
        "| Writes | none. The panel doesn't create, alter or delete anything |",
        "",
        "## What \"offer\" means here",
        "",
        "There is no promotional flag anywhere in the warehouse. `fact_price_change.sql`",
        "found the source's own `price_decreased` flag false on 100% of rows even when 152",
        "prices moved between two partitions. Every drop this panel shows is a",
        "`change_type = 'preco_alterado'` row with a negative `price_delta` — a REAL,",
        "OBSERVED price decrease, never a confirmed marketing campaign.",
        "",
        "## Parameters",
        "",
        "| Parameter | Type | Use |",
        "|---|---|---|",
        "| `%(inicio)s` | ISO date | lower bound on `snapshot_date`, inclusive |",
        "| `%(fim)s` | ISO date | upper bound on `snapshot_date`, inclusive |",
        "| `%(armazens)s` | comma-separated list | `wh = any(string_to_array(%(armazens)s, ','))` |",
        "| `%(termo)s` | `%...%` wildcard | `display_name ilike %(termo)s` — the wildcard "
        "lives in the bound VALUE, never concatenated into the SQL |",
        "",
        "Indicators marked **no date axis** ignore `inicio`/`fim`/`armazens`: "
        "`produtos_buscaveis` only takes `termo`, to feed the product search box.",
        "",
        "## Index",
        "",
    ]

    for grupo in sorted(grupos):
        linhas.append(f"- **{grupo}**")
        for indicador in grupos[grupo]:
            linhas.append(f"  - [{indicador.titulo}](#{indicador.chave})")
    linhas += [""]

    for grupo in sorted(grupos):
        linhas += [f"## {grupo}", ""]
        for indicador in grupos[grupo]:
            linhas += [
                f'<a id="{indicador.chave}"></a>',
                f"### {indicador.titulo}",
                "",
                "| | |",
                "|---|---|",
                f"| Key | `{indicador.chave}` |",
                f"| Question | {indicador.pergunta} |",
                f"| Source grain | `{indicador.grao}` |",
                f"| Data type | {indicador.tipo} |",
                f"| Marts | {', '.join(f'`{m}`' for m in indicador.marts)} |",
                f"| Date axis | {'yes' if indicador.datado else '**no**'} |",
                "",
            ]
            if indicador.armadilhas:
                linhas += ["**Gotchas when rebuilding in another tool**", ""]
                linhas += [f"{n}. {texto}" for n, texto in enumerate(indicador.armadilhas, 1)]
                linhas += [""]
            linhas += ["```sql", indicador.sql.strip(), "```", ""]

    linhas += [
        "---",
        "",
        "## Auxiliary queries",
        "",
        "Not business indicators. `FRESCOR` is what makes a new load **visible**: without",
        "it, the numbers change and nobody knows the catalog was re-cut.",
        "",
        "```sql",
        PI.FRESCOR.strip(),
        "```",
        "",
        "```sql",
        PI.JANELA.strip(),
        "```",
        "",
        "```sql",
        PI.ARMAZENS.strip(),
        "```",
        "",
    ]
    return "\n".join(linhas) + "\n"


def main() -> int:
    texto = render()
    temporario = DESTINO + ".tmp"
    with open(temporario, "w", encoding="utf-8") as arquivo:
        arquivo.write(texto)
    os.replace(temporario, DESTINO)
    print(f"escrito em ....... {os.path.relpath(DESTINO)}")
    print(f"origem sha256 .... {origem_sha256()}")
    print(f"indicadores ...... {len(PI.INDICADORES)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
